added webhooks and exported jks and changed files output path

diff --git a/.github/workflows/build-and-save.yml b/.github/workflows/build-and-save.yml
--- a/.github/workflows/build-and-save.yml
+++ b/.github/workflows/build-and-save.yml
@@ -12,23 +12,23 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    # - name: Send Webhook with Run ID
-    #   run: |
-    #     response=$(curl -X POST \
-    #       -H "Content-Type: application/json" \
-    #       -H "x-webhook-secret: ${{ secrets.WEBHOOK_SECRET_GITHUB }}" \
-    #       -d '{"run_id": "${{ github.run_id }}", "repoName": "${{ github.event.repository.name }}", "repoOwner": "${{ github.repository_owner }}", "type": "android", "appId": "${{ github.event.client_payload.appId }}", "userId": "${{ github.event.client_payload.userId }}"}' \
-    #       -w "%{http_code}" \
-    #       -o /dev/null \
-    #       -s \
-    #       https://user.mobtwintest.com/builder/workflow-webhook/build-info)
+    - name: Send Webhook with Run ID
+      run: |
+        response=$(curl -X POST \
+          -H "Content-Type: application/json" \
+          -H "x-webhook-secret: ${{ secrets.WEBHOOK_SECRET_GITHUB }}" \
+          -d '{"run_id": "${{ github.run_id }}", "repoName": "${{ github.event.repository.name }}", "repoOwner": "${{ github.repository_owner }}", "type": "android", "appId": "${{ github.event.client_payload.appId }}", "userId": "${{ github.event.client_payload.userId }}"}' \
+          -w "%{http_code}" \
+          -o /dev/null \
+          -s \
+          https://user.mobtwintest.com/builder/workflow-webhook/build-info)
     
     
-    #     if [ "$response" -ne 200 ]; then
-    #       echo "Webhook failed with status code $response"
-    #       exit 1
-    #     fi
-    #   shell: bash
+        if [ "$response" -ne 200 ]; then
+          echo "Webhook failed with status code $response"
+          exit 1
+        fi
+      shell: bash
     - name: Checkout code
       uses: actions/checkout@v3
 
@@ -95,7 +95,7 @@ jobs:
       run: |
         mv build/app/outputs/flutter-apk/app-release.apk ./
         mv build/app/outputs/bundle/release/app-release.aab ./
-        mv assets/db.json ./
+        mv android/app/${{ github.event.client_payload.key_alias }}-key.jks ./
  
     - name: Transfer apk to server
       uses: appleboy/scp-action@master
@@ -105,7 +105,7 @@ jobs:
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         port: 22
         source: "app-release.apk"
-        target: "/root/android"
+        target: /var/www/user_mobtwin/generated/${{ github.event.client_payload.userId }}/${{ github.event.client_payload.appId }}/${{ github.event.client_payload.versionCode }}/android
     - name: Transfer aab to server
       uses: appleboy/scp-action@master
       with:
@@ -114,17 +114,34 @@ jobs:
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         port: 22
         source: "app-release.aab"
-        target: "/root/android"
-    - name: Transfer db json to server
+        target: /var/www/user_mobtwin/generated/${{ github.event.client_payload.userId }}/${{ github.event.client_payload.appId }}/${{ github.event.client_payload.versionCode }}/android
+    - name: Transfer keystore json to server
       uses: appleboy/scp-action@master
       with:
         host: ${{ secrets.SERVER_HOST }}
         username: ${{ secrets.SERVER_USER }}
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         port: 22
-        source: "db.json"
-        target: "/root/android"
+        source: "${{ github.event.client_payload.key_alias }}-key.jks"
+        target: /var/www/user_mobtwin/generated/${{ github.event.client_payload.userId }}/${{ github.event.client_payload.appId }}/${{ github.event.client_payload.versionCode }}/android
+    - name: Send Webhook with Run ID
+      run: |
+        response=$(curl -X POST \
+          -H "Content-Type: application/json" \
+          -H "x-webhook-secret: ${{ secrets.WEBHOOK_SECRET_GITHUB }}" \
+          -d '{"run_id": "${{ github.run_id }}", "appId": "${{ github.event.client_payload.appId }}", "keystoreName":"${{ github.event.client_payload.key_alias }}-key.jks", "aabName":"app-release.aab", "apkName":"app-release.apk", "type":"android"}' \
+          -w "%{http_code}" \
+          -o /dev/null \
+          -s \
+          https://user.mobtwintest.com/builder/workflow-webhook/generated-paths)
     
+        echo "Response status code: $response"
+    
+        if [ "$response" -ne 200 ]; then
+          echo "Webhook failed with status code $response"
+          exit 1
+        fi
+      shell: bash
 
   # build-ios:
   #   name: Build iOS
